### PR TITLE
fix for CPAN RT#90972

### PR DESCRIPTION
**Pull request by spacebat**
Switched from Class::MOP wrapper functions to use Class::Load functions directly.
See https://rt.cpan.org/Ticket/Display.html?id=90972

### CODE REVIEW

**Comment by Ovid** [comment]
++

I was just going to write this. Thanks for doing it for me!

**Comment by nfoos** [comment]
I'm curious if/when this might get merged.  Just noticing deprecation warnings.

**Comment by toddr** [comment]
Ping

**Comment by willsheppard** [comment]
Bump - please merge

**Comment by davorg** [comment]
Any chance of getting this into a release soon? You're filling our logs with deprecation warnings :-(

**Comment by rafl** [comment]
Can I interest anyone in some co-maint?

**Comment by karenetheridge** [comment]
ok sure I'll do it.

**Comment by karenetheridge** [comment]
@davorg do you really need this module still? it was merged into Catalyst::Controller quite a while ago.

**Comment by jjn1056** [comment]
FWIF on CPAN these require CCAR:  https://metacpan.org/requires/distribution/Catalyst-Controller-ActionRole?sort=[[2,1]]

And a few of them I actually own, so I go and try to get them updated.  I think once we've fixed everything on CPAN that requires this as a dependency to not do so, we can probably add an official deprecation note.

**Comment by davorg** [comment]
@karenetheridge Turns out we are using Catalyst::ActionRole::JMS. So once that is fixed to not use ActionRole (and it just happens to be maintained by a colleague) we should be fine.

Thanks...

**Comment by karenetheridge** [comment]
On Thu, May 08, 2014 at 03:17:02PM -0700, John Napiorkowski wrote:

> FWIF on CPAN these require CCAR:  https://metacpan.org/requires/distribution/Catalyst-Controller-ActionRole?sort=[[2,1]]
> And a few of them I actually own, so I go and try to get them updated.  I think once we've fixed everything on CPAN that requires this as a dependency to not do so, we can probably add an official deprecation note.

Meh, I wouldn't wait to add the dep notice.  Just think of it as sending
the notice to yourself, too :)

**Comment by karenetheridge** [comment]
shipped!  rafl, you can close this now.

**Pull request closed without merging**
